// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVwXaZSLmRLUa0pVX8XdhOKXM7wNh-ehs',
    appId: '1:418119797137:web:c70278bd14c6eafb8d3230',
    messagingSenderId: '418119797137',
    projectId: 'flutterapp-13ab9',
    authDomain: 'flutterapp-13ab9.firebaseapp.com',
    storageBucket: 'flutterapp-13ab9.appspot.com',
    measurementId: 'G-VPEZXC77EQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnvVKlBRA_NjErlEoQeTeEl51V_9wq3Lw',
    appId: '1:418119797137:android:d02d1f20a4e63ee58d3230',
    messagingSenderId: '418119797137',
    projectId: 'flutterapp-13ab9',
    storageBucket: 'flutterapp-13ab9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_4lL633UhxrKZ0W7XC7eDkggibVZYqAg',
    appId: '1:418119797137:ios:196e5be918a8f9b58d3230',
    messagingSenderId: '418119797137',
    projectId: 'flutterapp-13ab9',
    storageBucket: 'flutterapp-13ab9.appspot.com',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_4lL633UhxrKZ0W7XC7eDkggibVZYqAg',
    appId: '1:418119797137:ios:a5af8246713863748d3230',
    messagingSenderId: '418119797137',
    projectId: 'flutterapp-13ab9',
    storageBucket: 'flutterapp-13ab9.appspot.com',
    iosBundleId: 'com.example.test1.RunnerTests',
  );
}
